### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by drizk1** [TidierOrg/TidierFiles.jl#1]
- [x] Read/write csv
- [x] Read/write tsv 
- [x] Read/write table
- [x] Read/write delim
- [x] Read/write excel
- [x] Read fwf
- [x] refine `fwf` helper functions to include name
- [x] stats support 
- [x] Add https support?
- [x] Docs - files are added it just needs to build
- [x] Docstrings

**Comment by drizk1** [comment]
hey @kdpsingh cranked thru most of the file types.  before i get started working on docs/docstrings,  i was wondering if u wanted them to have https get support (readr does for csv/tsv/delim). i have one for csv and it would be p easy to do, but i thought id get your take first as it would add one more dependency to the package. happy either way.

**Comment by kdpsingh** [comment]
Adding a dependency is fine if it means we can read in files from the web in all of the above formats.

**Comment by kdpsingh** [comment]
Would also love to add support for all formats supported in the haven R package (eg SAS and Stata files)

**Comment by drizk1** [comment]
adding support for SAS and Stata files is no problem. The [ReadStatTables.jl](https://github.com/junyuan-chen/ReadStatTables.jl) package made it ridiculously easy. so i already have support for all of them. The package made it so the function is identical `ReadStatTables.read_stat` and `ReadStatTables.writestat` for all 3, i just change the name. So if its the same function for each, should each have its own _sas, _sav, _dta or should it be a generic `read_stat/write_stat`? (theres no difference on labor for me)

**Comment by kdpsingh** [comment]
Great question! Let me think about this.

**Comment by kdpsingh** [comment]
Here's my idea:

Let's make specific function names to match the extension (read_sas, etc).

At some later point, we may also add a single read_file() and write_file() functions that infers the correct extension and calls the correct function specific to that extension.

**Comment by drizk1** [comment]
sounds good.  this repo might be nearly ready!

**Comment by drizk1** [comment]
I know its Monday and as a gainfully employed person, I assume you are busy but a quick update:  

Doctests clock in locally at 39.7s. I pared that down from 50, but I was unable to drop it further. Open to suggestions.

Files are in place for documentation, with a brief index.md written.
 
The only thing, when i was going thru the pkgtemplate.jl prompts I must have missed setting up the github tests? so theyre not running online. I am not sure how to enable that. 

Otherwise, I think this should be ready for transfer to TidierOrg / head to registry
```
Doctests: TidierFiles |    1      1  39.7s
```

**Comment by kdpsingh** [comment]
Amazing. I can help figure out the GitHub tests (need to set up GitHub actions).

Don't worry about the test completion time. 40 seconds is totally fine.

Can you move this repo over to TidierOrg?

**Comment by drizk1** [comment]
That would be awesome thank you! 

Just transferred it
